POST http://localhost:3000/uploads/file
Content-Type: multipart/form-data; boundary=WebKitFormBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoibWFya0AxNjMuY29tIiwiaWF0IjoxNzYwODc5Njg3LCJleHAiOjE3NjA4ODMyODcsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.9nq0cKVo5aU91EcLUYW4kaC2h1wKZpDNFPQHw7kmB_Q
file
--WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="test-image.jpg"
Content-Type: image/jpg

< ./test-image.jpg
--WebKitFormBoundary--