POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Mark",
    "lastName": "Doe",
    "email": "mark@163.com",
    "password": "Pawwword123@#!"
}




POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoibWFya0AxNjMuY29tIiwiaWF0IjoxNzYwNjY3MjEyLCJleHAiOjE3NjA2NzA4MTIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.9oLW9CPFRji21mEr831jUp0fwmrEdGGBF629jwCm0Ic

{
  "users": [
    {
      "firstName": "Mark",
      "lastName": "Doe",
      "email": "mark@163.com",
      "password": "Pawwword123@#!"
    },
    {
      "firstName": "Tom",
      "lastName": "Doe",
      "email": "tomk@163.com",
      "password": "Pawwword123@#!"
    }
  ]
}