POST http://localhost:3000/auth/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoibWFya0AxNjMuY29tIiwiaWF0IjoxNzYwNzc1ODIyLCJleHAiOjE3NjA3Nzk0MjIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Y374gvNYgB1SdR0i2m-s8Pu1t-MPZVNEe5_r23t-SzE

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTc2MDc3NTgyMiwiZXhwIjoxNzYwODYyMjIyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.-7zc0_sr5TfXDnk0W22i26y2L78fRnbuK2FTFQMY0PE"
}

// "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoibWFya0AxNjMuY29tIiwiaWF0IjoxNzYwNzc1ODIyLCJleHAiOjE3NjA3Nzk0MjIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Y374gvNYgB1SdR0i2m-s8Pu1t-MPZVNEe5_r23t-SzE",
//   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTc2MDc3NTgyMiwiZXhwIjoxNzYwODYyMjIyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.-7zc0_sr5TfXDnk0W22i26y2L78fRnbuK2FTFQMY0PE"